name: Word Submission – Create PR

on:
  issues:
    types: [labeled]

jobs:
  create-pr:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Parse issue body
        id: parse
        run: |
          TITLE="${{ github.event.issue.title }}"
          BODY="${{ github.event.issue.body }}"
          
          # Extract Tausug word, English meaning, category
          TAUSUG=$(echo "$BODY" | grep -oP '(?<=Tausug: ).*')
          ENGLISH=$(echo "$BODY" | grep -oP '(?<=English: ).*')
          CATEGORY=$(echo "$BODY" | grep -oP '(?<=Category: ).*')

          echo "tausug=$TAUSUG" >> $GITHUB_OUTPUT
          echo "english=$ENGLISH" >> $GITHUB_OUTPUT
          echo "category=$CATEGORY" >> $GITHUB_OUTPUT

      - name: Add word to dictionary.json
        run: |
          TAUSUG="${{ steps.parse.outputs.tausug }}"
          ENGLISH="${{ steps.parse.outputs.english }}"
          CATEGORY="${{ steps.parse.outputs.category }}"
          FILE="json/dictionary.json"

          # Use jq to add the word to the correct category
          jq --arg cat "$CATEGORY" \
             --arg key "$TAUSUG" \
             --arg val "$ENGLISH" \
             '.[$cat] += {($key): $val}' "$FILE" > tmp.json && mv tmp.json "$FILE"

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add ${{ steps.parse.outputs.tausug }} (from issue #${{ github.event.issue.number }})"
          title: "Add new word: ${{ steps.parse.outputs.tausug }} = ${{ steps.parse.outputs.english }}"
          body: |
            This PR adds the word submitted in issue #${{ github.event.issue.number }}.

            **Tausug:** ${{ steps.parse.outputs.tausug }}
            **English:** ${{ steps.parse.outputs.english }}
            **Category:** ${{ steps.parse.outputs.category }}

            Automatically created by the word-submission workflow.
          branch: add-word-${{ github.event.issue.number }}
          base: main
          labels: word-submission, automated-pr

      - name: Enable auto-merge on PR
        if: steps.create-pr.outputs.pull-request-number != ''
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER="${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Enabling auto-merge for PR #$PR_NUMBER"
          gh pr merge $PR_NUMBER --auto --merge
